# Generated by Django 3.1.7 on 2021-05-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210531_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestreservation',
            name='token',
            field=models.CharField(default='needreplacement', max_length=32, unique=True, verbose_name='Токен'),
            preserve_default=False,
        ),
    ]
