# Generated by Django 3.1.7 on 2021-06-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20210531_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='when_given',
            field=models.DateTimeField(verbose_name='Когда оставлен'),
        ),
    ]
